name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 * * * *"   # toutes les heures
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with WakaTime Metrics
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_OS: "True"
          SHOW_EDITORS: "True"
          SHOW_PROJECTS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LANGUAGE: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_TIMEZONE: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "True"
          SHOW_UPDATED_DATE: "True"

          SECTION_NAME: "waka"
          PULL_BRANCH_NAME: "main"
          PUSH_BRANCH_NAME: "main"

          COMMIT_BY_ME: "True"
          COMMIT_SINGLE: "True"
          COMMIT_MESSAGE: "update: WakaTime stats"
